### ISSUE TITLE
Inline data attribute does not fire

### ISSUE THREAD

**Issue by simondahla** [toddmotto/flare#4]
The inline `<a href="/promotions" data-flare='{
  "category": "KPI sections",
  "action": "click",
  "label": "Visit the promotions",
  "value": 4
}'>Click me</a>` does not fire a GA event. The custom flare `flare.emit()` forks totally fine.

Any idea how to solve this?

**Comment by davidspiess** [comment]
This should be mentioned in the docs. There is no hint that i have to call the `init()` function to make it work.
